[versions]
fabric-loader = "0.19.3"
fabric-api = "0.158.0+26.2"
fabric-kotlin = "1.13.12+kotlin.2.4.0"
arcade = "0.13.0-beta.6+26.2"
fabric-loom = "1.17-SNAPSHOT"
junit = "5.11.4"
junit-platform = "1.11.4"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
arcade-dimensions = { module = "net.casualchampionships:arcade-dimensions", version.ref = "arcade" }
arcade-event-registry = { module = "net.casualchampionships:arcade-event-registry", version.ref = "arcade" }
arcade-events-server = { module = "net.casualchampionships:arcade-events-server", version.ref = "arcade" }
arcade-extensions = { module = "net.casualchampionships:arcade-extensions", version.ref = "arcade" }
arcade-utils = { module = "net.casualchampionships:arcade-utils", version.ref = "arcade" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }

[bundles]
arcade = ["arcade-dimensions", "arcade-event-registry", "arcade-events-server", "arcade-extensions", "arcade-utils"]

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
