pluginManagement {
    repositories {
        maven { url = uri('https://maven.fabricmc.net/') }
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        create('libs') {
            from(files('libs.versions.toml'))
        }
    }
    repositories {
        maven { url = uri('https://maven.fabricmc.net/') }
        maven { url = uri('https://maven.supersanta.me/snapshots') }
        mavenCentral()
    }
}

rootProject.name = 'serenitea-pot'
